### ISSUE TITLE
The `global` variable is assumed to exist

### ISSUE THREAD

**Issue by Aaronius** [ljharb/global-cache#47]
Hi there! Here's the situation: [Vite](https://vitejs.dev/) is becoming a more popular bundler. Unlike some other bundlers (e.g, Webpack), Vite does not provide a built-in `global` variable. As such, if my project or any dependency uses global-cache, global-cache fails at runtime.

![image](https://user-images.githubusercontent.com/210820/145726763-3c2a78cc-2fb6-4d41-9241-6c93cac37033.png)

In our case, we use react-dates, which has an indirect dependency on global-cache:

![image](https://user-images.githubusercontent.com/210820/145726797-a4209d01-229a-47a8-9a15-cdab54f7f309.png)

global-cache fails because it assumes that `global` exists, which it may not because, as far as I'm aware, `global` was never part of any bundler/module spec outside of node. It was just a thing that some bundlers provided.

This issue is [discussed more in depth in the Vite repo](https://github.com/vitejs/vite/issues/2618).

While there are workarounds, ideally global-cache would not depend on `global`, rather than requiring users of Vite (or other bundlers that do not provide `global`) to implement those workarounds.

**Comment by ljharb** [comment]
This is a node module. Thus, `global` **always does exist**. Any bundler for node modules that doesn't provide it is fundamentally broken, and should be treated as such.

Historically, it was a thing EVERY bundler provided, because they're *node module bundlers*. Webpack 5 and vite, and maybe esbuild, are the only bundlers I know of that have broken with this defacto contract, at the expense of their users.

It's unfortunate that vite is unwilling to add `window.global = globalThis`, or rewrite all occurrences of `global` to `window`, as every bundler has done since the concept was first invented in browserify. 

If you insist on using a bundler that is fundamentally broken, and refuses to stop being user-hostile, then I'm afraid you'll continue to run into perfectly correct node packages that don't work for you.

**Comment by Aaronius** [comment]
Are you expecting your package to only be used in node? If so, then I suppose the react-with-styles-interface package should not have depended on it.

**Comment by ljharb** [comment]
No, I'm expecting that like every other node package that's used in other environments since the beginning of node, it will be transpiled by providing node globals as expected.

I'd suggest convincing vite to properly support bundling node modules; until it does, then I suppose you shouldn't be bundling any of them with vite.

**Comment by Aaronius** [comment]
I disagree with your position, but thank you for the communication.
